use serde_json::{Value, json};
use std::time::{SystemTime, UNIX_EPOCH};

use crate::settings::LlmProfile;

mod cache;
mod compress;
mod config;
mod summary;

#[cfg(test)]
mod tests;

pub(crate) use cache::{proxy_cache_dir, prune_cache_dir};
pub(crate) use config::ProxyOptimizationConfig;

pub(super) const OPTIMIZER_VERSION: &str = "v5";
pub(super) const CHARS_PER_TOKEN: usize = 4;
const MESSAGE_ENVELOPE_CHARS: usize = 24;

#[derive(Clone, Debug)]
pub(crate) struct OptimizedRequest {
    /// Request ready to send upstream.
    pub(crate) request: Value,
    // Optimizer outcome flags: asserted by the optimizer tests, not read in production.
    #[cfg_attr(not(test), allow(dead_code))]
    pub(crate) compressed: bool,
    #[cfg_attr(not(test), allow(dead_code))]
    pub(crate) local_summary: bool,
}

pub(crate) fn optimize_openai_request(request: Value, profile: &LlmProfile) -> OptimizedRequest {
    let config = ProxyOptimizationConfig::from_profile(profile);
    if !config.enabled {
        return OptimizedRequest {
            request,
            compressed: false,
            local_summary: false,
        };
    }

    let mut request = request;
    let Some(mut messages) = take_messages(&mut request) else {
        return OptimizedRequest {
            request,
            compressed: false,
            local_summary: false,
        };
    };

    let compressed = compress::compress_messages_in_place(&mut messages, &config);

    if estimate_messages_tokens(&messages) <= config.summary_threshold_tokens {
        set_messages(&mut request, messages);
        return OptimizedRequest {
            request,
            compressed,
            local_summary: false,
        };
    }

    let prefix_len = leading_system_count(&messages);
    let recent_start = recent_start_index(&messages, prefix_len, &config);
    if recent_start <= prefix_len {
        set_messages(&mut request, messages);
        return OptimizedRequest {
            request,
            compressed,
            local_summary: false,
        };
    }

    let summary = {
        let old_messages = &messages[prefix_len..recent_start];
        summary::local_summary_for_request(profile, &request, old_messages, &config)
    };
    let (prefix_messages, _old_messages, recent_messages) =
        split_into_segments(messages, prefix_len, recent_start);
    set_messages(
        &mut request,
        messages_with_summary(prefix_messages, &summary, recent_messages),
    );
    OptimizedRequest {
        request,
        compressed: true,
        local_summary: true,
    }
}

fn take_messages(request: &mut Value) -> Option<Vec<Value>> {
    let array = request.get_mut("messages")?.as_array_mut()?;
    Some(std::mem::take(array))
}

fn split_into_segments(
    mut messages: Vec<Value>,
    prefix_len: usize,
    recent_start: usize,
) -> (Vec<Value>, Vec<Value>, Vec<Value>) {
    let recent_messages = messages.split_off(recent_start);
    let old_messages = messages.split_off(prefix_len);
    (messages, old_messages, recent_messages)
}

fn leading_system_count(messages: &[Value]) -> usize {
    messages
        .iter()
        .take_while(|message| message_role(message) == "system")
        .count()
}

fn recent_start_index(
    messages: &[Value],
    prefix_len: usize,
    config: &ProxyOptimizationConfig,
) -> usize {
    let by_count = messages
        .len()
        .saturating_sub(config.keep_recent_messages)
        .max(prefix_len);
    let mut by_tokens = messages.len();
    let mut tokens = 0_usize;
    for index in (prefix_len..messages.len()).rev() {
        tokens = tokens.saturating_add(estimate_message_tokens(&messages[index]));
        by_tokens = index;
        if tokens >= config.keep_recent_tokens {
            break;
        }
    }
    let mut start = by_count.min(by_tokens).max(prefix_len);
    start = avoid_leading_tool_messages(messages, prefix_len, start);
    start
}

fn avoid_leading_tool_messages(messages: &[Value], prefix_len: usize, start: usize) -> usize {
    if start >= messages.len() || message_role(&messages[start]) != "tool" {
        return start;
    }
    let mut index = start;
    while index > prefix_len && message_role(&messages[index]) == "tool" {
        index -= 1;
    }
    index
}

pub(super) fn messages_with_summary(
    mut prefix_messages: Vec<Value>,
    summary: &str,
    mut recent_messages: Vec<Value>,
) -> Vec<Value> {
    prefix_messages.push(json!({
        "role": "system",
        "content": format!(
            "Compressed older conversation context generated by claudie OpenAI proxy:\n\n{}",
            summary.trim()
        )
    }));
    prefix_messages.append(&mut recent_messages);
    prefix_messages
}

pub(super) fn set_messages(request: &mut Value, messages: Vec<Value>) {
    if let Some(object) = request.as_object_mut() {
        object.insert("messages".to_string(), Value::Array(messages));
    }
}

pub(super) fn message_role(message: &Value) -> &str {
    message
        .get("role")
        .and_then(Value::as_str)
        .unwrap_or_default()
}

fn estimate_message_chars(message: &Value) -> usize {
    let content_chars = match message.get("content") {
        Some(Value::String(text)) => text.chars().count(),
        Some(Value::Array(blocks)) => blocks
            .iter()
            .map(|block| {
                block
                    .get("text")
                    .and_then(Value::as_str)
                    .or_else(|| block.as_str())
                    .map(|text| text.chars().count())
                    .unwrap_or(0)
            })
            .sum(),
        _ => 0,
    };
    let tool_calls_chars = message
        .get("tool_calls")
        .map(|value| value.to_string().chars().count())
        .unwrap_or(0);
    content_chars + tool_calls_chars + MESSAGE_ENVELOPE_CHARS
}

fn estimate_message_tokens(message: &Value) -> usize {
    estimate_message_chars(message).div_ceil(CHARS_PER_TOKEN)
}

fn estimate_messages_tokens(messages: &[Value]) -> usize {
    messages.iter().map(estimate_message_tokens).sum()
}

pub(super) fn now_millis() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_millis())
        .unwrap_or(0)
}
